In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import matplotlib.font_manager as fm
from matplotlib import rc

rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

In [92]:
df = pd.read_csv('/Users/zzgr/Desktop/zzgrSandaeteuk/PROJECT GAS STATION/Gas_Station.csv')
df.drop(columns='Unnamed: 0', inplace=True)
df

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),현대오일뱅크,02-487-2030,Y,-,1709,1829,-
1,서울특별시,방아다리주유소,서울 강동구 동남로 811 (명일동),SK에너지,02-442-5145,Y,-,1745,1865,1700
2,서울특별시,현대오일뱅크㈜직영 명일셀프주유소,서울 강동구 고덕로 168 (명일동),현대오일뱅크,02-3428-1739,Y,2033,1751,1851,-
3,서울특별시,구천면주유소,서울 강동구 구천면로 357 (암사동),현대오일뱅크,02-441-0536,N,-,1754,1855,-
4,서울특별시,대성석유(주)길동주유소,서울 강동구 천호대로 1168,GS칼텍스,02-474-7222,N,1995,1776,1869,1800
...,...,...,...,...,...,...,...,...,...,...
11291,서울특별시,(주)새서울네트웍스 제이제이주유소,서울 강남구 언주로 716,현대오일뱅크,02-518-5631,N,2448,2248,2347,-
11292,서울특별시,대청주유소,서울 강남구 개포로 654 (일원동),SK에너지,02-445-5500,N,2566,2266,2299,-
11293,서울특별시,SK논현주유소,서울 강남구 논현로 747 (논현동),SK에너지,02-511-0955,N,2620,2390,2420,1840
11294,서울특별시,갤러리아주유소,서울 강남구 압구정로 426,SK에너지,02-540-4965,N,2598,2399,2417,1840
11295,서울특별시,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),GS칼텍스,02-518-5141,N,2838,2598,2590,-

In [98]:
# 결측치 처리
temp = df[df['경유'] == '-']
temp

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
31,서울특별시,(주)자연에너지 국민주유소,서울 동대문구 답십리로 223 (답십리동),현대오일뱅크,02-2216-7155,N,-,-,-,-
135,서울특별시,지에스칼텍스(주)내곡주유소,서울 서초구 헌릉로 210,GS칼텍스,02-573-7878,N,-,-,-,-
257,서울특별시,한일주유소,서울 영등포구 도림로 486 (문래동3가),SK에너지,02-2679-1794,N,-,-,-,-
299,서울특별시,삼융주유소,서울 은평구 수색로 299 (수색동),SK에너지,02-307-3314,N,-,-,-,-
308,서울특별시,현대오일뱅크㈜직영 재동주유소,서울 종로구 율곡로 58 (경운동),현대오일뱅크,02-732-3968,N,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...
11031,경상남도,수동매일주유소,경남 함양군 수동면 거함대로 526,SK에너지,055-963-5181,N,-,-,-,-
11032,경상남도,추성주유소,경남 함양군 마천면 천왕봉로 1406,SK에너지,055-964-0417,N,-,-,-,-
11064,경상남도,해인만복주유소,경남 합천군 가야면 가야산로 1727,SK에너지,055-932-7226,N,-,-,-,-
11260,제주특별자치도,한림주유소,제주도 제주시 한림읍 한림로 699,SK에너지,064-796-2714,N,-,-,-,-
11261,제주특별자치도,창성주유소,제주 제주시 노형로 315 (노형동),GS칼텍스,064-713-8951,N,-,-,-,-

In [99]:
dropit = temp[temp['휘발유'] == '-']
dropit

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
31,서울특별시,(주)자연에너지 국민주유소,서울 동대문구 답십리로 223 (답십리동),현대오일뱅크,02-2216-7155,N,-,-,-,-
135,서울특별시,지에스칼텍스(주)내곡주유소,서울 서초구 헌릉로 210,GS칼텍스,02-573-7878,N,-,-,-,-
257,서울특별시,한일주유소,서울 영등포구 도림로 486 (문래동3가),SK에너지,02-2679-1794,N,-,-,-,-
299,서울특별시,삼융주유소,서울 은평구 수색로 299 (수색동),SK에너지,02-307-3314,N,-,-,-,-
308,서울특별시,현대오일뱅크㈜직영 재동주유소,서울 종로구 율곡로 58 (경운동),현대오일뱅크,02-732-3968,N,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...
11031,경상남도,수동매일주유소,경남 함양군 수동면 거함대로 526,SK에너지,055-963-5181,N,-,-,-,-
11032,경상남도,추성주유소,경남 함양군 마천면 천왕봉로 1406,SK에너지,055-964-0417,N,-,-,-,-
11064,경상남도,해인만복주유소,경남 합천군 가야면 가야산로 1727,SK에너지,055-932-7226,N,-,-,-,-
11260,제주특별자치도,한림주유소,제주도 제주시 한림읍 한림로 699,SK에너지,064-796-2714,N,-,-,-,-
11261,제주특별자치도,창성주유소,제주 제주시 노형로 315 (노형동),GS칼텍스,064-713-8951,N,-,-,-,-

In [100]:
dropit.reset_index(inplace=True)

In [101]:
dropidxlist = dropit['index'].tolist()

In [102]:
df.drop(index=dropidxlist, inplace=True)

In [103]:
# column type 변환 (obj -> int)
df['고급휘발유'].replace('-','0', inplace=True)
df['휘발유'].replace('-','0', inplace=True)
df['경유'].replace('-','0', inplace=True)
df['실내등유'].replace('-','0', inplace=True)

In [104]:
df['고급휘발유'] = df['고급휘발유'].astype(int)
df['휘발유'] = df['휘발유'].astype(int)
df['경유'] = df['경유'].astype(int)
df['실내등유'] = df['실내등유'].astype(int)

In [105]:
df

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),현대오일뱅크,02-487-2030,Y,0,1709,1829,0
1,서울특별시,방아다리주유소,서울 강동구 동남로 811 (명일동),SK에너지,02-442-5145,Y,0,1745,1865,1700
2,서울특별시,현대오일뱅크㈜직영 명일셀프주유소,서울 강동구 고덕로 168 (명일동),현대오일뱅크,02-3428-1739,Y,2033,1751,1851,0
3,서울특별시,구천면주유소,서울 강동구 구천면로 357 (암사동),현대오일뱅크,02-441-0536,N,0,1754,1855,0
4,서울특별시,대성석유(주)길동주유소,서울 강동구 천호대로 1168,GS칼텍스,02-474-7222,N,1995,1776,1869,1800
...,...,...,...,...,...,...,...,...,...,...
11291,서울특별시,(주)새서울네트웍스 제이제이주유소,서울 강남구 언주로 716,현대오일뱅크,02-518-5631,N,2448,2248,2347,0
11292,서울특별시,대청주유소,서울 강남구 개포로 654 (일원동),SK에너지,02-445-5500,N,2566,2266,2299,0
11293,서울특별시,SK논현주유소,서울 강남구 논현로 747 (논현동),SK에너지,02-511-0955,N,2620,2390,2420,1840
11294,서울특별시,갤러리아주유소,서울 강남구 압구정로 426,SK에너지,02-540-4965,N,2598,2399,2417,1840
11295,서울특별시,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),GS칼텍스,02-518-5141,N,2838,2598,2590,0

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10988 entries, 0 to 11295
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      10988 non-null  object
 1   상호      10988 non-null  object
 2   주소      10988 non-null  object
 3   상표      10988 non-null  object
 4   전화번호    10988 non-null  object
 5   셀프여부    10988 non-null  object
 6   고급휘발유   10988 non-null  int64
 7   휘발유     10988 non-null  int64
 8   경유      10988 non-null  int64
 9   실내등유    10988 non-null  int64
dtypes: int64(4), object(6)
memory usage: 944.3+ KB

In [107]:
# df 저장 후 팀원과 공유
# df.to_csv('Gas_Station_df.csv')

In [118]:
# 고급휘발유 판매하는 주유소의 지역별 수
premiumGas_df = df[df['고급휘발유'] != 0]
premiumGas_df
premiumGas_df['지역'].value_counts()

경기도        389
서울특별시      233
부산광역시       81
대구광역시       70
인천광역시       70
강원도         68
경상남도        66
충청남도        54
광주광역시       49
전라북도        48
경상북도        46
충청북도        42
대전광역시       40
전라남도        31
울산광역시       23
세종특별자치시      8
제주특별자치도      8
Name: 지역, dtype: int64

In [121]:
# 실내등유 판매하는 주유소의 지역별 수
indoorKer_df = df[df['실내등유'] != 0]
indoorKer_df
indoorKer_df['지역'].value_counts()

경기도        1190
경상북도        785
경상남도        667
충청남도        617
전라남도        524
전라북도        506
강원도         457
충청북도        418
제주특별자치도     169
인천광역시       149
대구광역시       148
부산광역시       141
서울특별시       140
울산광역시        96
광주광역시        87
대전광역시        70
세종특별자치시      33
Name: 지역, dtype: int64